Tests file created
tom-halpin/chatting-with-ChatGPT pull request #8
Opened 2023-06-04 17:21 UTC by Abraham12611

I created a new `tests` folder and moved the unittests file.

2023-06-06 11:33 UTC, tom-halpin requested changes
Following the move the tests are no longer working, also please include a CHANGELOG.md entry describing the change

To get the tests working in the new folder something like the following updates to the test script code are needed to fix the import statement for the class being tested

```python

import os
import sys
import unittest
from unittest.mock import patch, MagicMock
import openai

# Add the root folder to the Python module search path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from openAiCompletion import openAiCompletion
```

2023-06-06 16:41 UTC, Abraham12611 commented
Made requested changes

2023-06-06 17:09 UTC, tom-halpin commented on CHANGELOG.md
> +## [1.2.0] - 2023-06-06
```suggestion
## [1.2.1] - 2023-06-06
```

2023-06-06 17:11 UTC, tom-halpin requested changes
Thanks one minor change required see review for details

2023-06-06 17:11 UTC, tom-halpin commented on CHANGELOG.md
> +## [1.2.0] - 2023-06-06
Please update the version number in the change log

2023-06-07 08:20 UTC, merged

2023-06-07 08:21 UTC, tom-halpin commented
Thank you @Abraham12611